import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, Plus, Download, RefreshCw, Package, AlertTriangle, Clock3, Truck, Users, ShoppingCart, Trash2, Minus, MoreHorizontal, FileText, Bell, CheckCircle, Settings, Shield, Building2, UserCog, ClipboardList, ArrowRight, DollarSign, Receipt, TrendingUp } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/contexts/ToastContext';
import { formatCurrency, formatDate, formatDateTime, formatNumber, getExpiryStatus, downloadCSV, generateSaleNumber } from '@/lib/utils';
import type { Product, Inventory, ProductBatch, Supplier, Customer, Expense, Notification, Branch, CartItem } from '@/types';
import { Button } from '@/components/ui/Button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Input, Select, Textarea } from '@/components/ui/Input';
import { DataTable, Column } from '@/components/ui/DataTable';
import { Badge, StatusBadge } from '@/components/ui/Badge';
import { Modal } from '@/components/ui/Modal';
import { EmptyState, PageHeader, StatCard, PageLoader } from '@/components/ui/Common';

export function ProductsPage() {
  const { profile } = useAuth(); const { success, error } = useToast();
  const [rows, setRows] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ name:'', generic_name:'', sku:'', barcode:'', dosage_form:'Tablet', strength:'', unit:'Units', selling_price:'', cost_price:'', reorder_level:'20', is_prescription_required:false });
  const load = async () => { setLoading(true); const { data, error: e } = await supabase.from('products').select('*, category:product_categories(name)').eq('organization_id', profile?.organization_id || '').eq('is_active', true).order('name'); if(e) error(e.message); setRows((data || []) as Product[]); setLoading(false); };
  useEffect(()=>{ if(profile?.organization_id) load(); },[profile?.organization_id]);
  const save = async () => { if(!form.name || !profile?.organization_id) return; setSaving(true); const { error:e } = await supabase.from('products').insert({...form, organization_id:profile.organization_id, selling_price:Number(form.selling_price), cost_price:Number(form.cost_price), reorder_level:Number(form.reorder_level)}); setSaving(false); if(e) error(e.message); else { success('Product added successfully'); setOpen(false); setForm({name:'',generic_name:'',sku:'',barcode:'',dosage_form:'Tablet',strength:'',unit:'Units',selling_price:'',cost_price:'',reorder_level:'20',is_prescription_required:false}); load(); } };
  const columns: Column<Product>[] = [{key:'name',header:'Product',sortable:true,render:p=><div><p className="font-medium text-gray-900">{p.name}</p><p className="text-xs text-gray-400">{p.generic_name || p.sku || '—'}</p></div>},{key:'category',header:'Category',render:p=><Badge variant="default">{p.category?.name || 'Uncategorized'}</Badge>},{key:'barcode',header:'Barcode',render:p=><span className="font-mono text-xs">{p.barcode || '—'}</span>},{key:'selling_price',header:'Sell price',sortable:true,render:p=><span className="font-medium">{formatCurrency(p.selling_price)}</span>},{key:'cost_price',header:'Cost',render:p=>formatCurrency(p.cost_price)},{key:'is_prescription_required',header:'Rx',render:p=>p.is_prescription_required?<Badge variant="warning">Required</Badge>:<span className="text-gray-400">No</span>}];
  return <div><PageHeader title="Products" description={`${rows.length} active products in your catalog`} actions={<><Button variant="outline" size="sm" icon={<Download className="w-4 h-4"/>} onClick={()=>downloadCSV('products.csv',rows.map(p=>({name:p.name,sku:p.sku||'',barcode:p.barcode||'',selling_price:p.selling_price,cost_price:p.cost_price})))}>Export</Button><Button size="sm" icon={<Plus className="w-4 h-4"/>} onClick={()=>setOpen(true)}>Add product</Button></>}/><Card><CardContent><DataTable columns={columns} data={rows} loading={loading} searchable searchKeys={['name','sku','barcode','generic_name']} pageSize={15}/></CardContent></Card><Modal open={open} onClose={()=>setOpen(false)} title="Add product" size="lg" footer={<><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={saving} onClick={save}>Add product</Button></>}><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Input label="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Input label="Generic name" value={form.generic_name} onChange={e=>setForm({...form,generic_name:e.target.value})}/><Input label="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><Input label="Barcode" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/><Input label="Dosage form" value={form.dosage_form} onChange={e=>setForm({...form,dosage_form:e.target.value})}/><Input label="Strength" value={form.strength} onChange={e=>setForm({...form,strength:e.target.value})}/><Input label="Selling price (KES)" type="number" value={form.selling_price} onChange={e=>setForm({...form,selling_price:e.target.value})} required/><Input label="Cost price (KES)" type="number" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})} required/><Input label="Reorder level" type="number" value={form.reorder_level} onChange={e=>setForm({...form,reorder_level:e.target.value})}/><label className="flex items-center gap-2 text-sm text-gray-700 mt-6"><input type="checkbox" checked={form.is_prescription_required} onChange={e=>setForm({...form,is_prescription_required:e.target.checked})} className="rounded border-gray-300 text-primary-600"/> Prescription required</label></div></Modal></div>;
}

export function InventoryPage({ mode='stock' }: { mode?: 'stock'|'low'|'expiry'|'movements' }) {
  const { profile } = useAuth(); const [rows,setRows]=useState<Inventory[]>([]); const [batches,setBatches]=useState<(ProductBatch & {product?:Product})[]>([]); const [loading,setLoading]=useState(true); const load=async()=>{setLoading(true); if(mode==='expiry'){const {data}=await supabase.from('product_batches').select('*, product:products(name,sku)').eq('organization_id',profile?.organization_id||'').order('expiry_date');setBatches((data||[]) as any);}else{const {data}=await supabase.from('inventory').select('*, product:products(name,sku,reorder_level,cost_price,selling_price)').eq('organization_id',profile?.organization_id||'').order('quantity');setRows((data||[]) as any);}setLoading(false)}; useEffect(()=>{if(profile?.organization_id)load()},[profile?.organization_id,mode]);
  const filtered=mode==='low'?rows.filter(r=>r.quantity <= (r.product?.reorder_level||0)):rows; const title=mode==='low'?'Low stock':mode==='expiry'?'Expiry management':mode==='movements'?'Stock movements':'Stock'; const desc=mode==='expiry'?'Monitor expired and near-expiry batches':mode==='low'?'Products below their reorder levels':'Current stock by branch';
  const stockCols:Column<Inventory>[]=[{key:'product',header:'Product',sortable:true,render:r=><div><p className="font-medium text-gray-900">{r.product?.name}</p><p className="text-xs text-gray-400">{r.product?.sku}</p></div>},{key:'branch',header:'Branch',render:r=><span className="text-gray-500">Main branch</span>},{key:'quantity',header:'Units',sortable:true,render:r=><span className={r.quantity==0?'text-error-600 font-bold':r.quantity <= (r.product?.reorder_level||0)?'text-warning-600 font-semibold':'font-medium'}>{formatNumber(r.quantity)}</span>},{key:'reorder_level',header:'Reorder at',render:r=>formatNumber(r.product?.reorder_level)},{key:'value',header:'Stock value',render:r=>formatCurrency(r.quantity*(r.product?.cost_price||0))},{key:'status',header:'Status',render:r=>r.quantity===0?<Badge variant="error">Out of stock</Badge>:r.quantity <= (r.product?.reorder_level||0)?<Badge variant="warning">Low stock</Badge>:<Badge variant="success">Healthy</Badge>}];
  const batchCols:Column<ProductBatch & {product?:Product}>[]=[{key:'product',header:'Product',render:r=><div><p className="font-medium text-gray-900">{r.product?.name}</p><p className="text-xs text-gray-400">{r.product?.sku}</p></div>},{key:'batch_number',header:'Batch',render:r=><span className="font-mono text-xs">{r.batch_number}</span>},{key:'expiry_date',header:'Expiry',sortable:true,render:r=>formatDate(r.expiry_date)},{key:'quantity_current',header:'Units',render:r=>formatNumber(r.quantity_current)},{key:'status',header:'Status',render:r=>{const s=getExpiryStatus(r.expiry_date);return <Badge variant={s.color==='expired'||s.color==='critical'?'error':s.color==='warning'?'warning':'success'}>{s.label}</Badge>}}];
  return <div><PageHeader title={title} description={desc} actions={<Button variant="outline" size="sm" icon={<RefreshCw className="w-4 h-4"/>} onClick={load}>Refresh</Button>}/><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4"><StatCard label="Total units" value={formatNumber(rows.reduce((s,r)=>s+r.quantity,0))} icon={<Package className="w-5 h-5"/>} color="primary"/><StatCard label="Inventory value" value={formatCurrency(rows.reduce((s,r)=>s+r.quantity*(r.product?.cost_price||0),0))} icon={<DollarSign className="w-5 h-5"/>} color="secondary"/><StatCard label="Low stock" value={formatNumber(rows.filter(r=>r.quantity <= (r.product?.reorder_level||0)).length)} icon={<AlertTriangle className="w-5 h-5"/>} color="warning"/><StatCard label="Expiry watch" value={formatNumber(batches.filter(b=>getExpiryStatus(b.expiry_date).daysLeft<=90).length)} icon={<Clock3 className="w-5 h-5"/>} color="error"/></div><Card><CardContent>{mode==='expiry'?<DataTable columns={batchCols} data={batches} loading={loading} searchable searchKeys={['batch_number']} />:<DataTable columns={stockCols} data={filtered} loading={loading} searchable searchKeys={['product']} />}</CardContent></Card></div>;
}

export function SuppliersPage(){const {profile}=useAuth();const [rows,setRows]=useState<Supplier[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{if(profile?.organization_id)supabase.from('suppliers').select('*').eq('organization_id',profile.organization_id).order('name').then(({data})=>{setRows((data||[]) as Supplier[]);setLoading(false)})},[profile?.organization_id]);const cols:Column<Supplier>[]=[{key:'name',header:'Supplier',sortable:true,render:s=><div><p className="font-medium text-gray-900">{s.name}</p><p className="text-xs text-gray-400">{s.contact_person||'No contact assigned'}</p></div>},{key:'phone',header:'Phone'},{key:'payment_terms',header:'Terms',render:s=><Badge variant="default">{s.payment_terms||'—'}</Badge>},{key:'credit_limit',header:'Credit limit',render:s=>formatCurrency(s.credit_limit)},{key:'outstanding_balance',header:'Outstanding',render:s=><span className={s.outstanding_balance>0?'text-error-600 font-semibold':'text-success-600'}>{formatCurrency(s.outstanding_balance)}</span>},{key:'status',header:'Status',render:s=><StatusBadge status={s.status}/>}];return <div><PageHeader title="Suppliers" description={`${rows.length} suppliers in your network`} actions={<Button size="sm" icon={<Plus className="w-4 h-4"/>}>Add supplier</Button>}/><Card><CardContent><DataTable columns={cols} data={rows} loading={loading} searchable searchKeys={['name','contact_person','phone']} /></CardContent></Card></div>}

export function CustomersPage(){const {profile}=useAuth();const [rows,setRows]=useState<Customer[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{if(profile?.organization_id)supabase.from('customers').select('*').eq('organization_id',profile.organization_id).order('name').then(({data})=>{setRows((data||[]) as Customer[]);setLoading(false)})},[profile?.organization_id]);const cols:Column<Customer>[]=[{key:'name',header:'Customer',sortable:true,render:c=><div><p className="font-medium text-gray-900">{c.name}</p><p className="text-xs text-gray-400">{c.customer_number||'—'}</p></div>},{key:'phone',header:'Phone'},{key:'email',header:'Email'},{key:'outstanding_balance',header:'Balance',render:c=><span className={c.outstanding_balance>0?'text-warning-600 font-semibold':'text-gray-600'}>{formatCurrency(c.outstanding_balance)}</span>},{key:'status',header:'Status',render:c=><StatusBadge status={c.status}/>}];return <div><PageHeader title="Customers" description="Customer accounts, credit and purchase history" actions={<Button size="sm" icon={<Plus className="w-4 h-4"/>}>Add customer</Button>}/><Card><CardContent><DataTable columns={cols} data={rows} loading={loading} searchable searchKeys={['name','phone','email','customer_number']}/></CardContent></Card></div>}

export function SuppliersPlaceholder(){return <SuppliersPage/>}
